name: Python autotests

on: [push]

jobs:
  run-tests:
    runs-on: ubunty-latest
    name: Run autotests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: run tests
        run: pytest
        
