name: Python autotests

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose test set
        required: True
        type: choice
        default: Smoke
        options:
          - Smoke
          - Regression
          - Extended
          - All
       

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4
      - name: Set up python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install playwright
        run: playwright install
      - name: run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest
      - name: run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke
      - name: run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression
      - name: run extended tests
        if: "github.event.inputs.deployment_target == 'extended'"
        run: pytest -m extended
      
      
